name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@main
        with:
          version: 'latest'
          service_account_key: ${{ secrets.JAN_GCP_SA_KEY }}
          project_id: upday-react-library

      - name: Configure Docker CLI
        run: |
          gcloud auth configure-docker

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.JAN_DOCKER_USERNAME }}
          password: ${{ secrets.JAN_DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t gcr.io/upday-react-library/upday-react-library:latest .
          docker push gcr.io/upday-react-library/upday-react-library:latest