name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add your build and test steps here
      # ...

      - name: Publish to npm registry
        run: npm publish --access public
        with:
          username: ${{ secrets.JAN_NPM_USERNAME }}
          password: ${{ secrets.JAN_NPM_PASSWORD }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JAN_NPM_TOKEN }}
